TRUNCATE TABLE client_product_events RESTART IDENTITY CASCADE;
TRUNCATE TABLE clients_360 RESTART IDENTITY CASCADE;
TRUNCATE TABLE client_taxonomy_summary RESTART IDENTITY CASCADE;
TRUNCATE TABLE master_key RESTART IDENTITY CASCADE;
DELETE FROM sync_log WHERE source = 'csv_upload';
